#它的launch文件传进去是不需要命名空间的
align_depth.enable: false #对齐深度图到彩色图
gyro_fps: 200 #陀螺仪频率
accel_fps: 100 #加速度计频率
unite_imu_method: 1 #linear_interpolation
enable_accel: false #使能加速度计
enable_gyro: false #使能陀螺仪
enable_sync: false  #使能同步
enable_depth: false #使能深度图
# rgb_camera.color_profile: 640x480x60 #彩色图分辨率和频率
rgb_camera.color_profile: 848x480x60
